// this file was generated by gomacro command: import _i "gioui.org/op/clip"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	clip "gioui.org/op/clip"
)

// reflection: allow interpreted code to import "gioui.org/op/clip"
func init() {
	imports.Packages["gioui.org/op/clip"] = imports.Package{
	Name: "clip",
	Binds: map[string]r.Value{
		"BevelJoin":	r.ValueOf(clip.BevelJoin),
		"FlatCap":	r.ValueOf(clip.FlatCap),
		"RoundCap":	r.ValueOf(clip.RoundCap),
		"RoundJoin":	r.ValueOf(clip.RoundJoin),
		"SquareCap":	r.ValueOf(clip.SquareCap),
		"UniformRRect":	r.ValueOf(clip.UniformRRect),
	}, Types: map[string]r.Type{
		"Border":	r.TypeOf((*clip.Border)(nil)).Elem(),
		"Dash":	r.TypeOf((*clip.Dash)(nil)).Elem(),
		"DashSpec":	r.TypeOf((*clip.DashSpec)(nil)).Elem(),
		"Op":	r.TypeOf((*clip.Op)(nil)).Elem(),
		"Outline":	r.TypeOf((*clip.Outline)(nil)).Elem(),
		"Path":	r.TypeOf((*clip.Path)(nil)).Elem(),
		"PathSpec":	r.TypeOf((*clip.PathSpec)(nil)).Elem(),
		"RRect":	r.TypeOf((*clip.RRect)(nil)).Elem(),
		"Rect":	r.TypeOf((*clip.Rect)(nil)).Elem(),
		"Stroke":	r.TypeOf((*clip.Stroke)(nil)).Elem(),
		"StrokeCap":	r.TypeOf((*clip.StrokeCap)(nil)).Elem(),
		"StrokeJoin":	r.TypeOf((*clip.StrokeJoin)(nil)).Elem(),
		"StrokeStyle":	r.TypeOf((*clip.StrokeStyle)(nil)).Elem(),
	}, 
	}
}
