// this file was generated by gomacro command: import _i "gioui.org/io/clipboard"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	clipboard "gioui.org/io/clipboard"
)

// reflection: allow interpreted code to import "gioui.org/io/clipboard"
func init() {
	imports.Packages["gioui.org/io/clipboard"] = imports.Package{
	Name: "clipboard",
	Types: map[string]r.Type{
		"Event":	r.TypeOf((*clipboard.Event)(nil)).Elem(),
		"ReadOp":	r.TypeOf((*clipboard.ReadOp)(nil)).Elem(),
		"WriteOp":	r.TypeOf((*clipboard.WriteOp)(nil)).Elem(),
	}, 
	}
}
