// this file was generated by gomacro command: import _i "gioui.org/x/colorpicker"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	colorpicker "gioui.org/x/colorpicker"
)

// reflection: allow interpreted code to import "gioui.org/x/colorpicker"
func init() {
	imports.Packages["gioui.org/x/colorpicker"] = imports.Package{
	Name: "colorpicker",
	Binds: map[string]r.Value{
		"Mux":	r.ValueOf(colorpicker.Mux),
		"NewMuxState":	r.ValueOf(colorpicker.NewMuxState),
		"Picker":	r.ValueOf(colorpicker.Picker),
	}, Types: map[string]r.Type{
		"C":	r.TypeOf((*colorpicker.C)(nil)).Elem(),
		"D":	r.TypeOf((*colorpicker.D)(nil)).Elem(),
		"MuxOption":	r.TypeOf((*colorpicker.MuxOption)(nil)).Elem(),
		"MuxState":	r.TypeOf((*colorpicker.MuxState)(nil)).Elem(),
		"MuxStyle":	r.TypeOf((*colorpicker.MuxStyle)(nil)).Elem(),
		"PickerStyle":	r.TypeOf((*colorpicker.PickerStyle)(nil)).Elem(),
		"State":	r.TypeOf((*colorpicker.State)(nil)).Elem(),
	}, Wrappers: map[string][]string{
		"C":	[]string{"Data","Refs","Reset","Version","Write","Write1","Write2",},
		"MuxState":	[]string{"Changed","Layout",},
		"MuxStyle":	[]string{"Changed","Color",},
		"PickerStyle":	[]string{"Alpha","Blue","CaretCoords","CaretPos","Changed","Color","Delete","Events","Focus","Focused","Green","Insert","Len","Move","NumLines","PaintCaret","PaintText","Red","SetColor","SetText","Text","WithPalette",},
		"State":	[]string{"CaretCoords","CaretPos","Delete","Events","Focus","Focused","Insert","Len","Move","NumLines","PaintCaret","PaintText","SetText","Text",},
	}, 
	}
}
