// this file was generated by gomacro command: import _i "gioui.org/x/haptic"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	haptic "gioui.org/x/haptic"
)

// reflection: allow interpreted code to import "gioui.org/x/haptic"
func init() {
	imports.Packages["gioui.org/x/haptic"] = imports.Package{
	Name: "haptic",
	Binds: map[string]r.Value{
		"NewBuzzer":	r.ValueOf(haptic.NewBuzzer),
	}, Types: map[string]r.Type{
		"Buzzer":	r.TypeOf((*haptic.Buzzer)(nil)).Elem(),
	}, 
	}
}
