// this file was generated by gomacro command: import _i "gioui.org/app/headless"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	headless "gioui.org/app/headless"
)

// reflection: allow interpreted code to import "gioui.org/app/headless"
func init() {
	imports.Packages["gioui.org/app/headless"] = imports.Package{
	Name: "headless",
	Binds: map[string]r.Value{
		"NewWindow":	r.ValueOf(headless.NewWindow),
	}, Types: map[string]r.Type{
		"Window":	r.TypeOf((*headless.Window)(nil)).Elem(),
	}, 
	}
}
