// this file was generated by gomacro command: import _i "gioui.org/io/key"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	key "gioui.org/io/key"
)

// reflection: allow interpreted code to import "gioui.org/io/key"
func init() {
	imports.Packages["gioui.org/io/key"] = imports.Package{
	Name: "key",
	Binds: map[string]r.Value{
		"ModAlt":	r.ValueOf(key.ModAlt),
		"ModCommand":	r.ValueOf(key.ModCommand),
		"ModCtrl":	r.ValueOf(key.ModCtrl),
		"ModShift":	r.ValueOf(key.ModShift),
		"ModShortcut":	r.ValueOf(key.ModShortcut),
		"ModSuper":	r.ValueOf(key.ModSuper),
		"NameDeleteBackward":	r.ValueOf(key.NameDeleteBackward),
		"NameDeleteForward":	r.ValueOf(key.NameDeleteForward),
		"NameDownArrow":	r.ValueOf(key.NameDownArrow),
		"NameEnd":	r.ValueOf(key.NameEnd),
		"NameEnter":	r.ValueOf(key.NameEnter),
		"NameEscape":	r.ValueOf(key.NameEscape),
		"NameHome":	r.ValueOf(key.NameHome),
		"NameLeftArrow":	r.ValueOf(key.NameLeftArrow),
		"NamePageDown":	r.ValueOf(key.NamePageDown),
		"NamePageUp":	r.ValueOf(key.NamePageUp),
		"NameReturn":	r.ValueOf(key.NameReturn),
		"NameRightArrow":	r.ValueOf(key.NameRightArrow),
		"NameTab":	r.ValueOf(key.NameTab),
		"NameUpArrow":	r.ValueOf(key.NameUpArrow),
		"Press":	r.ValueOf(key.Press),
		"Release":	r.ValueOf(key.Release),
	}, Types: map[string]r.Type{
		"EditEvent":	r.TypeOf((*key.EditEvent)(nil)).Elem(),
		"Event":	r.TypeOf((*key.Event)(nil)).Elem(),
		"FocusEvent":	r.TypeOf((*key.FocusEvent)(nil)).Elem(),
		"FocusOp":	r.TypeOf((*key.FocusOp)(nil)).Elem(),
		"InputOp":	r.TypeOf((*key.InputOp)(nil)).Elem(),
		"Modifiers":	r.TypeOf((*key.Modifiers)(nil)).Elem(),
		"SoftKeyboardOp":	r.TypeOf((*key.SoftKeyboardOp)(nil)).Elem(),
		"State":	r.TypeOf((*key.State)(nil)).Elem(),
	}, Untypeds: map[string]string{
		"NameDeleteBackward":	"string:⌫",
		"NameDeleteForward":	"string:⌦",
		"NameDownArrow":	"string:↓",
		"NameEnd":	"string:⇲",
		"NameEnter":	"string:⌤",
		"NameEscape":	"string:⎋",
		"NameHome":	"string:⇱",
		"NameLeftArrow":	"string:←",
		"NamePageDown":	"string:⇟",
		"NamePageUp":	"string:⇞",
		"NameReturn":	"string:⏎",
		"NameRightArrow":	"string:→",
		"NameTab":	"string:⇥",
		"NameUpArrow":	"string:↑",
	}, 
	}
}
