// this file was generated by gomacro command: import _i "gioui.org/font/opentype"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	opentype "gioui.org/font/opentype"
)

// reflection: allow interpreted code to import "gioui.org/font/opentype"
func init() {
	imports.Packages["gioui.org/font/opentype"] = imports.Package{
	Name: "opentype",
	Binds: map[string]r.Value{
		"Parse":	r.ValueOf(opentype.Parse),
		"ParseCollection":	r.ValueOf(opentype.ParseCollection),
		"ParseCollectionReaderAt":	r.ValueOf(opentype.ParseCollectionReaderAt),
	}, Types: map[string]r.Type{
		"Collection":	r.TypeOf((*opentype.Collection)(nil)).Elem(),
		"Font":	r.TypeOf((*opentype.Font)(nil)).Elem(),
	}, 
	}
}
