// this file was generated by gomacro command: import _i "gioui.org/x/outlay"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	outlay "gioui.org/x/outlay"
)

// reflection: allow interpreted code to import "gioui.org/x/outlay"
func init() {
	imports.Packages["gioui.org/x/outlay"] = imports.Package{
	Name: "outlay",
	Binds: map[string]r.Value{
		"Item":	r.ValueOf(outlay.Item),
	}, Types: map[string]r.Type{
		"Animation":	r.TypeOf((*outlay.Animation)(nil)).Elem(),
		"Cell":	r.TypeOf((*outlay.Cell)(nil)).Elem(),
		"Fan":	r.TypeOf((*outlay.Fan)(nil)).Elem(),
		"FanItem":	r.TypeOf((*outlay.FanItem)(nil)).Elem(),
		"Grid":	r.TypeOf((*outlay.Grid)(nil)).Elem(),
		"GridElement":	r.TypeOf((*outlay.GridElement)(nil)).Elem(),
		"GridWrap":	r.TypeOf((*outlay.GridWrap)(nil)).Elem(),
		"Table":	r.TypeOf((*outlay.Table)(nil)).Elem(),
	}, Wrappers: map[string][]string{
		"Animation":	[]string{"Hours","Microseconds","Milliseconds","Minutes","Nanoseconds","Round","Seconds","String","Truncate",},
		"Fan":	[]string{"Animating","Hours","Microseconds","Milliseconds","Minutes","Nanoseconds","Progress","Round","Seconds","SetDuration","Start","String","Truncate",},
	}, 
	}
}
