// this file was generated by gomacro command: import _i "gioui.org/io/profile"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	profile "gioui.org/io/profile"
)

// reflection: allow interpreted code to import "gioui.org/io/profile"
func init() {
	imports.Packages["gioui.org/io/profile"] = imports.Package{
	Name: "profile",
	Types: map[string]r.Type{
		"Event":	r.TypeOf((*profile.Event)(nil)).Elem(),
		"Op":	r.TypeOf((*profile.Op)(nil)).Elem(),
	}, 
	}
}
