// this file was generated by gomacro command: import _i "gioui.org/io/router"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	router "gioui.org/io/router"
)

// reflection: allow interpreted code to import "gioui.org/io/router"
func init() {
	imports.Packages["gioui.org/io/router"] = imports.Package{
	Name: "router",
	Binds: map[string]r.Value{
		"TextInputClose":	r.ValueOf(router.TextInputClose),
		"TextInputKeep":	r.ValueOf(router.TextInputKeep),
		"TextInputOpen":	r.ValueOf(router.TextInputOpen),
	}, Types: map[string]r.Type{
		"Router":	r.TypeOf((*router.Router)(nil)).Elem(),
		"TextInputState":	r.TypeOf((*router.TextInputState)(nil)).Elem(),
	}, 
	}
}
