// this file was generated by gomacro command: import _i "gioui.org/io/system"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	system "gioui.org/io/system"
)

// reflection: allow interpreted code to import "gioui.org/io/system"
func init() {
	imports.Packages["gioui.org/io/system"] = imports.Package{
	Name: "system",
	Binds: map[string]r.Value{
		"CommandBack":	r.ValueOf(system.CommandBack),
		"StagePaused":	r.ValueOf(system.StagePaused),
		"StageRunning":	r.ValueOf(system.StageRunning),
	}, Types: map[string]r.Type{
		"CommandEvent":	r.TypeOf((*system.CommandEvent)(nil)).Elem(),
		"CommandType":	r.TypeOf((*system.CommandType)(nil)).Elem(),
		"DestroyEvent":	r.TypeOf((*system.DestroyEvent)(nil)).Elem(),
		"FrameEvent":	r.TypeOf((*system.FrameEvent)(nil)).Elem(),
		"Insets":	r.TypeOf((*system.Insets)(nil)).Elem(),
		"Stage":	r.TypeOf((*system.Stage)(nil)).Elem(),
		"StageEvent":	r.TypeOf((*system.StageEvent)(nil)).Elem(),
	}, 
	}
}
