// this file was generated by gomacro command: import _i "gioui.org/unit"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package giopkgs

import (
	r "reflect"
	"github.com/cosmos72/gomacro/imports"
	unit "gioui.org/unit"
)

// reflection: allow interpreted code to import "gioui.org/unit"
func init() {
	imports.Packages["gioui.org/unit"] = imports.Package{
	Name: "unit",
	Binds: map[string]r.Value{
		"Add":	r.ValueOf(unit.Add),
		"Dp":	r.ValueOf(unit.Dp),
		"Max":	r.ValueOf(unit.Max),
		"Px":	r.ValueOf(unit.Px),
		"Sp":	r.ValueOf(unit.Sp),
		"UnitDp":	r.ValueOf(unit.UnitDp),
		"UnitPx":	r.ValueOf(unit.UnitPx),
		"UnitSp":	r.ValueOf(unit.UnitSp),
	}, Types: map[string]r.Type{
		"Metric":	r.TypeOf((*unit.Metric)(nil)).Elem(),
		"Unit":	r.TypeOf((*unit.Unit)(nil)).Elem(),
		"Value":	r.TypeOf((*unit.Value)(nil)).Elem(),
	}, 
	}
}
